// Plain-English explanations for someone new to each business: what every agent does, what every task means,
// what each approval does, and a glossary of the jargon that shows up on the floor.

export const AGENT_EXPLAIN = {
  manager: 'The Big Boss. Every few hours it looks at everything (money, approvals waiting, what failed) and decides which agents should work on what next. It can only assign work; it can\'t spend money or approve anything for you.',
  risk: 'The safety officer. It watches deadlines, spending limits and error rates, and raises an alarm (or pauses something) when a limit is crossed.',
  improve: 'Looks for steps that keep getting stuck and suggests fixes. It only suggests; you decide.',
  experiments: 'Turns an idea into a small, cheap test with a clear goal ("5 sales in 14 days") and a stop rule, so we don\'t waste money on things that don\'t work.',
  scout: 'Finds local businesses (bakeries, salons, plumbers…) on Google Maps that might need a better website, and records where it found each fact.',
  inspector: 'Opens each business\'s current website on a phone and a computer, scores how good it is, and finds a public way to contact the owner. A bad or missing website means they\'re a good prospect.',
  designer: 'Builds a private sample homepage for the business, so the owner can see what a better site would look like before paying anything.',
  qa: 'Double-checks the sample site before anyone sees it: works on phones, loads fast, phone number is tappable, no mistakes.',
  postmaster: 'Writes the outreach email (with a before/after picture) and follow-ups, and proposals when someone is interested. Nothing is sent until you approve it, or until a campaign you approved covers it.',
  caller: 'Writes a short call script and the facts you need for a phone call. You make the call; AI calling stays off unless a business has given written permission.',
  sports: 'Turns official KJ\'s Picks results into marketing posts. Every post includes the required 21+ and problem-gambling notices, and nothing is posted without your approval.',
  marketer: 'Plans campaigns: who we\'re trying to reach, where, the message, and the budget limit.',
  social: 'Writes social media posts for each platform.',
  etsy: 'Researches what printable products people are buying on Etsy, how many competitors there are, and whether we could make money after Etsy\'s fees.',
  merchant: 'Designs original printable products and writes honest Etsy listings for them.',
  fulfillment: 'Watches real Etsy orders and makes sure each customer gets what they paid for.',
  ds_research: 'Looks for product niches people are actively buying (dropshipping = we sell it online; a supplier ships it straight to the customer).',
  ds_product: 'Scores each product idea and rejects risky ones (fragile, restricted, health claims, trademark problems).',
  ds_supplier: 'Checks suppliers: real business, product cost, shipping time, tracking, return policy. Asks for a sample before we sell anything.',
  ds_store: 'Builds an accurate product page in the Shopify store, with true shipping times and policies.',
  ds_orders: 'Checks every paid order for fraud and profit before it goes to the supplier, and holds anything suspicious for you.',
  re_market: 'Reads the local housing market: prices, how fast homes sell, what investors are buying.',
  re_leads: 'Researches property owners who might want to sell (from public records you import) and verifies the facts.',
  re_underwrite: 'Estimates what a house is worth after repairs, what repairs cost, and the most we could safely offer.',
  re_deals: 'Prepares offers and tracks contract deadlines. Every offer needs your approval and a professional review; it never signs anything for you.',
  re_buyers: 'Keeps a list of investors who asked to hear about deals, and matches deals to them.',
  brand_dev: 'Creates small online brands (a name, a look, who it\'s for) for social media and YouTube channels.',
  account_prov: 'Gives you step-by-step instructions to create each brand\'s social accounts (you create them yourself), then checks they\'re connected.',
  strategy: 'Plans what each brand posts and when (the content calendar).',
  scriptwriter: 'Researches facts and writes short video scripts, keeping the source link for every fact.',
  creative: 'Makes the video or image from our own graphics and captions.',
  editor: 'Tightens the video: pacing, captions, readability.',
  content_qa: 'Blocks anything with an unsourced claim, a mistake, or a rights problem before it can be published.',
  publisher: 'Posts approved content to the right account, exactly once.',
  community: 'Reads comments and sends real questions to your inbox.',
  growth: 'Measures views and results from the platforms themselves (no guessing).',
  packaging: 'Writes accurate titles, descriptions and thumbnails.',
  monetize: 'Tracks which brands could earn money and how, separating money actually earned from money that\'s only possible.',
  opportunity: 'Researches new business ideas and writes a short memo: who pays, why, what a cheap test would look like, and the biggest risk.',
  research: 'Answers market questions with web research and cited sources.',
  support: 'Reads replies in the inbox, sorts them (interested, question, not interested, unsubscribe) and drafts answers for your approval.',
  finance: 'Keeps the money ledger (what was actually collected vs estimated) and sends your morning text.',
  learning: 'Looks back weekly at what actually made money and what didn\'t.',
  capital: 'Suggests how to split money that has actually been collected between businesses, always keeping a safety reserve.',
};

export const TASK_EXPLAIN = {
  plan: 'Reviewing every business and deciding what each agent should do next.',
  plan_idea: 'Turning your idea into a step-by-step plan, using only things the team can actually do, for your approval.',
  build_site: 'Building a one-page website someone on the team asked for. It stays private until you approve publishing it.',
  research: 'Searching the web to answer a business question, keeping links to every source.',
  find_prospects: 'Searching Google Maps for local businesses of one type (for example, bakeries in Bryan) that might need a website.',
  audit_site: 'Loading the business\'s website on a phone and a computer to see what\'s broken: slow, hard to read, no call button. A weak site is a reason they might buy a new one.',
  design_page: 'Building a private sample homepage for this business so the owner can see a better version of their site.',
  check_site: 'Testing the sample site on a phone and a computer before anyone sees it.',
  draft_email: 'Writing a short, honest email to the business owner with a before/after picture of their site.',
  run_followups: 'Checking who hasn\'t replied yet and is due a polite follow-up (only within rules you approved).',
  draft_proposal: 'Writing a proposal: price, what\'s included, timeline and a payment link.',
  process_inbox: 'Reading new email replies and sorting them: interested, question, not interested, or unsubscribe.',
  prepare_call: 'Writing a short call script and the key facts for a phone call you\'ll make.',
  record_outcome: 'Saving what happened on a call and setting up the next step.',
  research_products: 'Checking which printable products sell on Etsy and whether we\'d make money after fees.',
  build_digital_product: 'Designing an original printable and writing its Etsy listing for your review.',
  sync_orders: 'Pulling new orders and shipping updates from Etsy.',
  sync_picks: 'Importing the official picks and results from KJ\'s Picks.',
  draft_content: 'Writing marketing posts from the official picks, with the required notices.',
  propose_opportunities: 'Researching new business ideas and writing short memos about them.',
  plan_campaign: 'Planning a marketing campaign: who, where, what message, and the spending limit.',
  write_posts: 'Writing social posts.',
  research_niches: 'Looking for product categories people are actively buying right now.',
  evaluate_product: 'Scoring a product idea for demand, profit and risk.',
  find_suppliers: 'Checking suppliers for real cost, shipping speed, tracking and returns.',
  build_listing: 'Creating an accurate product page in the store.',
  review_order: 'Checking a paid order for fraud and profit before it goes to the supplier.',
  sync_shopify_orders: 'Checking tracking numbers for open orders.',
  market_report: 'Summarizing the local housing market from data and cited sources.',
  import_leads: 'Loading property owner records you provided and checking them.',
  underwrite: 'Estimating the home\'s value after repairs, repair costs, and the most we could safely offer.',
  plan_outreach: 'Preparing a respectful letter to a homeowner, for your approval.',
  prepare_offer: 'Preparing an offer for your approval (and a professional\'s review).',
  match_buyers: 'Finding investors on our opt-in list whose criteria match this property.',
  check_risks: 'Checking deadlines, budgets and error rates against your limits.',
  allocation_report: 'Looking at how much money has actually been collected and suggesting how to split it.',
  weekly_learning: 'Reviewing the week: what made money, what didn\'t, and why.',
  design_experiment: 'Designing a small, cheap test with a clear goal and a stop rule.',
  find_bottlenecks: 'Looking for steps that keep getting stuck.',
  propose_brand: 'Researching an audience and proposing a brand name, look and plan.',
  prepare_accounts: 'Writing step-by-step instructions for you to create the brand\'s accounts.',
  check_accounts: 'Checking that each brand account is still connected.',
  plan_calendar: 'Planning which videos and posts go out and when.',
  write_script: 'Researching facts and writing a short video script with sources.',
  produce: 'Making the video from our own graphics and captions.',
  edit: 'Editing the video for pacing and readable captions.',
  package: 'Writing the title, description and thumbnail.',
  review: 'Checking the content for unsourced claims and mistakes before it can be published.',
  publish_due: 'Posting content that\'s scheduled and approved, exactly once.',
  measure: 'Collecting views and results from the platforms.',
  check_comments: 'Reading new comments for real questions.',
  evaluate_brands: 'Checking each brand against the success goals you approved.',
  brand_report: 'Writing a weekly report on one brand.',
};

export const APPROVAL_EXPLAIN = {
  email: 'Approving sends this one email to the business. Emails can\'t be unsent.',
  followup: 'Approving sends a follow-up email to someone who hasn\'t replied yet.',
  reply: 'Approving sends this reply to the person who wrote to us.',
  proposal: 'Approving sends a proposal with a price and a payment link. Nothing is charged until they choose to pay.',
  email_campaign: 'A "standing approval": instead of approving each email, you approve the rules (which areas, which business types, how many per day). Emails that fit these exact rules then go out automatically until it ends or you pause it.',
  calling_campaign: 'A standing approval for consented AI calls within these exact rules.',
  marketing_campaign: 'A standing approval for marketing within these exact limits and budget.',
  fulfillment_policy: 'A standing approval for sending paid orders to the supplier automatically, but only when they meet these limits (profit, cost, no fraud flags).',
  product: 'Approving publishes this product listing on Etsy.',
  content: 'Approving lets this post go out (or be marked ready for you to post).',
  social_post: 'Approving lets this post go out.',
  campaign: 'Approving starts this campaign within its stated budget.',
  ds_launch: 'Approving puts this product on sale in the store and lets matching orders be sent to the supplier within the limits shown.',
  sample_purchase: 'Approving lets us buy one sample to check quality before selling it. That money is spent.',
  re_letter: 'Approving mails or emails this letter to the homeowner.',
  re_offer: 'A binding offer: if the seller signs, we are legally committed. It needs your signature and a professional review first.',
  re_deal_package: 'Approving sends this deal\'s details to investors who asked to receive deals.',
  brand_experiment: 'Approving starts a small, time-limited test for this brand, within the budget shown.',
  brand_content: 'A standing approval: content for this brand that passes quality checks can publish to its own accounts without asking each time.',
  content_publish: 'Approving publishes this item to the brand account shown.',
  ceo_promotion: 'Approving gives this brand its own "CEO agent" that reports to the Big Boss. It gets no new spending power.',
  budget_allocation: 'Approving sets aside this money for the purpose shown.',
  opportunity_experiment: 'Approving starts a small test of this new business idea, with a spending cap and a stop rule. Anything the memo says other agents should make (a website, a brand, research) is requested automatically.',
  project_plan: 'Approving lets the Big Boss hand each step of this plan to the agent who does that kind of work. Steps cost a little AI time. Anything public (a website going live, posts, emails) still comes back to you for approval.',
  site_publish: 'Approving puts this page on the internet at the address shown. You can unpublish it later.',
};

export const GLOSSARY = {
  'pipeline': 'Money we might get (proposals sent, deals under contract). Not real until it\'s paid.',
  'collected': 'Money that actually arrived (confirmed by Stripe, Etsy, Shopify or you).',
  'contribution': 'What\'s left from the money we collected after paying for ads, products, fees and AI. Shown as an estimate.',
  'margin': 'The share of the sale price we keep after costs. A $34 sale with $24 of costs has about a 29% margin.',
  'standing approval': 'Approving a set of rules once, so routine actions that fit those exact rules don\'t need your OK each time.',
  'lead': 'A business or person who might become a customer.',
  'lead score': 'Our 0–100 guess of how likely a business is to want our service (higher = better prospect).',
  'prospect': 'A business we think might buy from us.',
  'follow-up': 'A polite second email when someone hasn\'t replied.',
  'proposal': 'A written offer with a price, what\'s included, and a payment link.',
  'qa': 'Quality assurance: checking work for mistakes before anyone sees it.',
  'cac': 'Customer acquisition cost: what it costs (ads, time) to win one customer.',
  'arv': 'After-repair value: what a house should sell for once fixed up.',
  'mao': 'Maximum allowable offer: the most we can offer and still leave room for repairs, costs and profit.',
  'comps': 'Comparable homes nearby, used to estimate value. In Texas sale prices aren\'t public, so we use listing prices and say so.',
  'earnest money': 'A deposit a buyer puts down when signing a home contract. The system never sends it for you.',
  'option period': 'In Texas contracts, a short window when the buyer can cancel for any reason.',
  'wholesaling': 'Getting a home under contract and selling that contract to an investor for a fee.',
  'assignment fee': 'The fee we\'d earn for passing a home contract to an investor.',
  'dropshipping': 'We sell a product online; a supplier ships it straight to the customer, so we never hold stock.',
  'pod': 'Print-on-demand: a printer makes and ships the item only after someone buys it.',
  'fulfillment': 'Getting a paid order to the customer.',
  'conversion': 'When someone takes the step you wanted (replied, bought, signed up).',
  'reply rate': 'The share of people we emailed who wrote back.',
  'ctr': 'Click-through rate: the share of people who saw something and clicked it.',
  'can-spam': 'The US email law: honest subject lines, a real address, and an easy way to opt out.',
  'tcpa': 'The US law on calls and texts: no automated or AI-voice calls without written consent.',
  'a2p 10dlc': 'The registration US carriers require before a business can send texts from a normal phone number.',
  'workflow': 'One piece of work tracked from start to finish (for example, one business from "found" to "paid").',
  'handoff': 'When one agent finishes its step and passes the work to the next agent.',
  'stalled': 'Work that hasn\'t moved for longer than it normally should.',
  'idle': 'No task running right now. The agent waits for its next scheduled job or assignment.',
  'blocked': 'Can\'t continue until something is fixed (an error, a missing connection, a failed check).',
  'brand': 'A small online identity (name, look, audience) with its own social accounts.',
  'landing page': 'A single web page about one offer, with one clear button (call, email or book).',
  'oauth': 'Signing in on Google\'s own page so we never see or store your password.',
};

/** Glossary terms that appear in a piece of text (case-insensitive, whole words). */
export function termsIn(text, limit = 6) {
  const t = String(text || '').toLowerCase();
  return Object.entries(GLOSSARY).filter(([k]) => new RegExp(`(^|[^a-z])${k.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&')}([^a-z]|$)`).test(t)).slice(0, limit);
}
